### ISSUE TITLE
32-bit ARM types / intrinsics like `uint8x4_t` and `vdupq_n_u8` are not stable yet

### ISSUE THREAD

**Issue by sdroege** [cberner/raptorq#216]
Build with 1.94.1:

```
error[E0425]: cannot find type `uint8x16_t` in this scope
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:902:32
    |
902 | unsafe fn store_neon(ptr: *mut uint8x16_t, value: uint8x16_t) {
    |                                ^^^^^^^^^^ not found in this scope
    |
help: consider importing this struct
    |
  1 + use std::arch::arm::uint8x16_t;
    |
error[E0425]: cannot find type `uint8x16_t` in this scope
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:902:51
    |
902 | unsafe fn store_neon(ptr: *mut uint8x16_t, value: uint8x16_t) {
    |                                                   ^^^^^^^^^^ not found in this scope
    |
help: consider importing this struct
    |
  1 + use std::arch::arm::uint8x16_t;
    |
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:182:28
    |
182 |         let shuffle_mask = vld1q_u8([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1].as_ptr());
    |                            ^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:183:31
    |
183 |         let bit_select_mask = vld1q_u8(
    |                               ^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:189:27
    |
189 |         let scalar_neon = vdupq_n_u8(scalar.byte());
    |                           ^^^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:192:49
    |
192 |         for i in 0..(remaining / mem::size_of::<uint8x16_t>()) {
    |                                                 ^^^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:194:29
    |
194 |             let other_vec = vld1q_dup_u16(other_neon.add(other_batch_start_index + i));
    |                             ^^^^^^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:195:28
    |
195 |             let other_vec: uint8x16_t = mem::transmute(other_vec);
    |                            ^^^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:197:29
    |
197 |             let other_vec = vandq_u8(other_vec, bit_select_mask);
    |                             ^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:201:29
    |
201 |             let other_vec = vcgeq_u8(other_vec, vdupq_n_u8(1));
    |                             ^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:201:49
    |
201 |             let other_vec = vcgeq_u8(other_vec, vdupq_n_u8(1));
    |                                                 ^^^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:203:27
    |
203 |             let product = vandq_u8(other_vec, scalar_neon);
    |                           ^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:206:28
    |
206 |             let self_vec = vld1q_u8(self_neon_ptr.add(i * mem::size_of::<uint8x16_t>()));
    |                            ^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:206:74
    |
206 |             let self_vec = vld1q_u8(self_neon_ptr.add(i * mem::size_of::<uint8x16_t>()));
    |                                                                          ^^^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:207:26
    |
207 |             let result = veorq_u8(self_vec, product);
    |                          ^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:208:47
    |
208 |             store_neon((self_neon_ptr as *mut uint8x16_t).add(i), result);
    |                                               ^^^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:152:13
    |
152 |         use std::arch::arm::*;
    |             ^^^^^^^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:497:20
    |
497 |         let mask = vdupq_n_u8(0x0F);
    |                    ^^^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:500:25
    |
500 |         let low_table = vld1q_u8(OCTET_MUL_LOW_BITS[scalar.byte() as usize].as_ptr());
    |                         ^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:502:24
    |
502 |         let hi_table = vld1q_u8(OCTET_MUL_HI_BITS[scalar.byte() as usize].as_ptr());
    |                        ^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:504:52
    |
504 |         for i in 0..(octets.len() / mem::size_of::<uint8x16_t>()) {
    |                                                    ^^^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:507:28
    |
507 |             let self_vec = vld1q_u8(self_neon_ptr.add(i * mem::size_of::<uint8x16_t>()));
    |                            ^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:507:74
    |
507 |             let self_vec = vld1q_u8(self_neon_ptr.add(i * mem::size_of::<uint8x16_t>()));
    |                                                                          ^^^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:508:23
    |
508 |             let low = vandq_u8(self_vec, mask);
    |                       ^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
  |
  = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:511:22
    |
511 |             let hi = vandq_u8(hi, mask);
    |                      ^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:513:26
    |
513 |             let result = veorq_u8(hi_result, low_result);
    |                          ^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:514:47
    |
514 |             store_neon((self_neon_ptr as *mut uint8x16_t).add(i), result);
    |                                               ^^^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:517:55
    |
517 |         let remainder = octets.len() % mem::size_of::<uint8x16_t>();
    |                                                       ^^^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:494:13
    |
494 |         use std::arch::arm::*;
    |             ^^^^^^^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:678:20
    |
678 |         let mask = vdupq_n_u8(0x0F);
    |                    ^^^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:682:25
    |
682 |         let low_table = vld1q_u8(OCTET_MUL_LOW_BITS[scalar.byte() as usize].as_ptr());
    |                         ^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:684:24
    |
684 |         let hi_table = vld1q_u8(OCTET_MUL_HI_BITS[scalar.byte() as usize].as_ptr());
    |                        ^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:686:52
    |
686 |         for i in 0..(octets.len() / mem::size_of::<uint8x16_t>()) {
    |                                                    ^^^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:689:29
    |
689 |             let other_vec = vld1q_u8(other_neon_ptr.add(i * mem::size_of::<uint8x16_t>()));
    |                             ^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:689:76
    |
689 |             let other_vec = vld1q_u8(other_neon_ptr.add(i * mem::size_of::<uint8x16_t>()));
    |                                                                            ^^^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:690:23
    |
690 |             let low = vandq_u8(other_vec, mask);
    |                       ^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:693:22
    |
693 |             let hi = vandq_u8(hi, mask);
    |                      ^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:695:29
    |
695 |             let other_vec = veorq_u8(hi_result, low_result);
    |                             ^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:699:28
    |
699 |             let self_vec = vld1q_u8(self_neon_ptr.add(i * mem::size_of::<uint8x16_t>()));
    |                            ^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:699:74
    |
699 |             let self_vec = vld1q_u8(self_neon_ptr.add(i * mem::size_of::<uint8x16_t>()));
    |                                                                          ^^^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:700:26
    |
700 |             let result = veorq_u8(self_vec, other_vec);
    |                          ^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:702:47
    |
702 |             store_neon((self_neon_ptr as *mut uint8x16_t).add(i), result);
    |                                               ^^^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:705:55
    |
705 |         let remainder = octets.len() % mem::size_of::<uint8x16_t>();
    |                                                       ^^^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:675:13
    |
675 |         use std::arch::arm::*;
    |             ^^^^^^^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:910:24
    |
910 |         let reinterp = vreinterpretq_u64_u8(value);
    |                        ^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:907:13
    |
907 |         use std::arch::arm::*;
    |             ^^^^^^^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:934:28
    |
934 |             let self_vec = vld1q_u8(self_neon_ptr.add(i * mem::size_of::<uint8x16_t>()));
    |                            ^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:934:74
    |
934 |             let self_vec = vld1q_u8(self_neon_ptr.add(i * mem::size_of::<uint8x16_t>()));
    |                                                                          ^^^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:936:29
    |
936 |             let other_vec = vld1q_u8(other_neon_ptr.add(i * mem::size_of::<uint8x16_t>()));
    |                             ^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:936:76
    |
936 |             let other_vec = vld1q_u8(other_neon_ptr.add(i * mem::size_of::<uint8x16_t>()));
    |                                                                            ^^^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:937:26
    |
937 |             let result = veorq_u8(self_vec, other_vec);
    |                          ^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:939:47
    |
939 |             store_neon((self_neon_ptr as *mut uint8x16_t).add(i), result);
    |                                               ^^^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more information
error[E0658]: use of unstable library feature `stdarch_arm_neon_intrinsics`
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:926:13
    |
926 |         use std::arch::arm::*;
    |             ^^^^^^^^^^^^^^
    |
    = note: see issue #111800 <https://github.com/rust-lang/rust/issues/111800> for more informationerror[E0425]: cannot find function `vqtbl1q_u8` in this scope
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:196:29
    |
196 |             let other_vec = vqtbl1q_u8(other_vec, shuffle_mask);
    |                             ^^^^^^^^^^
    |
   --> /rustc/4a4ef493e3a1488c6e321570238084b38948f6db/library/core/src/../../stdarch/crates/core_arch/src/arm_shared/neon/generated.rs:73433:0
    |
    = note: similarly named function `vtbl1_u8` defined here
help: a function with a similar name exists
    |
196 -             let other_vec = vqtbl1q_u8(other_vec, shuffle_mask);
196 +             let other_vec = vtbl1_u8(other_vec, shuffle_mask);
    |
error[E0425]: cannot find function `vqtbl1q_u8` in this scope
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:509:30
    |
509 |             let low_result = vqtbl1q_u8(low_table, low);
    |                              ^^^^^^^^^^
    |
   --> /rustc/4a4ef493e3a1488c6e321570238084b38948f6db/library/core/src/../../stdarch/crates/core_arch/src/arm_shared/neon/generated.rs:73433:0
    |
    = note: similarly named function `vtbl1_u8` defined here
help: a function with a similar name exists
    |
509 -             let low_result = vqtbl1q_u8(low_table, low);
509 +             let low_result = vtbl1_u8(low_table, low);
    |
error[E0425]: cannot find function `vqtbl1q_u8` in this scope
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:512:29
    |
512 |             let hi_result = vqtbl1q_u8(hi_table, hi);
    |                             ^^^^^^^^^^
    |
   --> /rustc/4a4ef493e3a1488c6e321570238084b38948f6db/library/core/src/../../stdarch/crates/core_arch/src/arm_shared/neon/generated.rs:73433:0
    |
    = note: similarly named function `vtbl1_u8` defined here
help: a function with a similar name exists
    |
512 -             let hi_result = vqtbl1q_u8(hi_table, hi);
512 +             let hi_result = vtbl1_u8(hi_table, hi);
    |
error[E0425]: cannot find function `vqtbl1q_u8` in this scope
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:691:30
    |
691 |             let low_result = vqtbl1q_u8(low_table, low);
    |                              ^^^^^^^^^^
    |
   --> /rustc/4a4ef493e3a1488c6e321570238084b38948f6db/library/core/src/../../stdarch/crates/core_arch/src/arm_shared/neon/generated.rs:73433:0
    |
    = note: similarly named function `vtbl1_u8` defined here
help: a function with a similar name exists
    |
691 -             let low_result = vqtbl1q_u8(low_table, low);
691 +             let low_result = vtbl1_u8(low_table, low);
    |
error[E0425]: cannot find function `vqtbl1q_u8` in this scope
   --> /builds/gstreamer/cerbero/cerbero-sources/gst-plugins-rs/cargo-vendor/raptorq/src/octets.rs:694:29
    |
694 |             let hi_result = vqtbl1q_u8(hi_table, hi);
    |                             ^^^^^^^^^^
    |
   --> /rustc/4a4ef493e3a1488c6e321570238084b38948f6db/library/core/src/../../stdarch/crates/core_arch/src/arm_shared/neon/generated.rs:73433:0
    |
    = note: similarly named function `vtbl1_u8` defined here
help: a function with a similar name exists
    |
694 -             let hi_result = vqtbl1q_u8(hi_table, hi);
694 +             let hi_result = vtbl1_u8(hi_table, hi);
    |
Some errors have detailed explanations: E0425, E0658.
For more information about an error, try `rustc --explain E0425`.
```
